# Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking

# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands

after-startup-command = [
    # JankyBorders has a built-in detection of already running process,
    # so it won't be run twice on AeroSpace restart
    'exec-and-forget borders active_color=0xffffff00 inactive_color=0xff494d64 width=5.0'
]

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodness#disable-hide-app
automatically-unhide-macos-hidden-apps = false

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       5
outer.bottom =     5
outer.top =        5
outer.right =      5

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
# You can uncomment the following lines to open up terminal with alt + enter shortcut (like in i3)
# alt-enter = '''exec-and-forget osascript -e '
# tell application "Terminal"
#     do script
#     activate
# end tell'
# '''

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
alt-ctrl-s = 'layout tiles horizontal'
alt-ctrl-x = 'layout tiles vertical'
alt-ctrl-t = 'layout accordion horizontal vertical'

alt-ctrl-shift-space = 'layout floating tiling'

alt-shift-ctrl-x = 'split vertical'
alt-shift-ctrl-s = 'split horizontal'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
alt-ctrl-h = 'focus left'
alt-ctrl-j = 'focus down'
alt-ctrl-k = 'focus up'
alt-ctrl-l = 'focus right'

alt-ctrl-f = 'fullscreen'

alt-ctrl-minus = 'resize smart -100'
alt-ctrl-equal = 'resize smart +100'

# alt--h = ['join-with left', 'mode main']
# alt--j = ['join-with down', 'mode main']
# alt--k = ['join-with up', 'mode main']
# alt--l = ['join-with right', 'mode main']

# See: https://nikitabobko.github.io/AeroSpace/commands#move
alt-shift-ctrl-h = 'move left'
alt-shift-ctrl-j = 'move down'
alt-shift-ctrl-k = 'move up'
alt-shift-ctrl-l = 'move right'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
# main screen
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'
# left screen
alt-minus = 'workspace 11'
alt-leftSquareBracket = 'workspace 12'
# right screen
alt-equal = 'workspace 13'
alt-rightSquareBracket = 'workspace 14'
# sidecar or other
alt-backspace = 'workspace 15'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
# main screen
alt-shift-ctrl-1 = ["move-node-to-workspace 1", "workspace 1"]
alt-shift-ctrl-2 = ["move-node-to-workspace 2", "workspace 2"]
alt-shift-ctrl-3 = ["move-node-to-workspace 3", "workspace 3"]
alt-shift-ctrl-4 = ["move-node-to-workspace 4", "workspace 4"]
alt-shift-ctrl-5 = ["move-node-to-workspace 5", "workspace 5"]
alt-shift-ctrl-6 = ["move-node-to-workspace 6", "workspace 6"]
alt-shift-ctrl-7 = ["move-node-to-workspace 7", "workspace 7"]
alt-shift-ctrl-8 = ["move-node-to-workspace 8", "workspace 8"]
alt-shift-ctrl-9 = ["move-node-to-workspace 9", "workspace 9"]
alt-shift-ctrl-0 = ["move-node-to-workspace 10", "workspace 10"]
# left screen
alt-shift-ctrl-minus = ["move-node-to-workspace 11", "workspace 11"]
alt-shift-ctrl-leftSquareBracket = ["move-node-to-workspace 12", "workspace 12"]
# right screen
alt-shift-ctrl-equal = ["move-node-to-workspace 13", "workspace 13"]
alt-shift-ctrl-rightSquareBracket = ["move-node-to-workspace 14", "workspace 14"]
# sidecar or other
alt-shift-ctrl-backspace = ["move-node-to-workspace 15", "workspace 15"]

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
alt-shift-o = 'mode floating'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-fort
alt-tab = 'focus-back-and-forth'
# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
alt-shift-tab = 'workspace-back-and-forth'

# See: https://nikitabobko.github.io/AeroSpace/commands#mode
alt-shift-semicolon = 'mode service'

[workspace-to-monitor-force-assignment]
1 = ['LG ULTRAWIDE', 'DELL S3221QS', 'Built-in Retina Display']
2 = ['LG ULTRAWIDE', 'DELL S3221QS', 'Built-in Retina Display']
3 = ['LG ULTRAWIDE', 'DELL S3221QS', 'Built-in Retina Display']
4 = ['LG ULTRAWIDE', 'DELL S3221QS', 'Built-in Retina Display']
5 = ['LG ULTRAWIDE', 'DELL S3221QS', 'Built-in Retina Display']
6 = ['LG ULTRAWIDE', 'DELL S3221QS', 'Built-in Retina Display']
7 = ['LG ULTRAWIDE', 'DELL S3221QS', 'Built-in Retina Display']
8 = ['LG ULTRAWIDE', 'DELL S3221QS', 'Built-in Retina Display']
9 = ['LG ULTRAWIDE', 'DELL S3221QS', 'Built-in Retina Display']
10 = ['LG ULTRAWIDE', 'DELL S3221QS', 'Built-in Retina Display']

11 = ['^LG SDQHD \(1\).*', 'Built-in Retina Display']
12 = ['^LG SDQHD \(1\).*', 'Built-in Retina Display']

13 = ['^LG SDQHD \(2\).*', 'Built-in Retina Display']
14 = ['^LG SDQHD \(2\).*', 'Built-in Retina Display']

15 = ['Sidecar Display.*', 'DELL.*', 'Built-in Retina Display', 'main']

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

ctrl-space = 'mode management'
[mode.management.binding]
f = ['fullscreen', 'mode main']

minus = 'resize smart -50'
equal = 'resize smart +50'

# sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
#s = ['layout sticky tiling', 'mode main']

# -----------------------------------------------------------------------
# Apps assignment
##### 1
[[on-window-detected]]
if.app-id = 'com.microsoft.AzureVpnMac'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-id = 'com.att.ATTGNCMac'
run = 'move-node-to-workspace 1'

##### 2
[[on-window-detected]]
if.app-id = 'com.apple.Safari.WebApp.3CCE0A2A-9A72-46D6-B405-C592D481C594'
run = 'move-node-to-workspace 2'

##### 3
[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = 'move-node-to-workspace 3'

##### 4
[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-id = 'org.jkiss.dbeaver.core.product'
run = 'move-node-to-workspace 4'

##### 5
[[on-window-detected]]
if.app-id = 'com.citrix.receiver.icaviewer.mac'
run = 'move-node-to-workspace 5'

##### 9
[[on-window-detected]]
if.app-id = 'com.apple.iCal'
run = 'move-node-to-workspace 9'

[[on-window-detected]]
if.app-id = 'com.apple.reminders'
run = 'move-node-to-workspace 9'

[[on-window-detected]]
if.app-id = 'com.rambox'
run = 'move-node-to-workspace 10'

[[on-window-detected]]
if.app-id = 'com.hnc.Discord'
run = 'move-node-to-workspace 0'

# -----------------------------------------------------------------------
# See: https://nikitabobko.github.io/AeroSpace/goodness#popular-apps-ids
# mdls -name kMDItemCFBundleIdentifier -r 'app'
# Autofloating
[[on-window-detected]]
if.app-id = 'com.apple.finder'
check-further-callbacks = true
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.1password.1password'
check-further-callbacks = true
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.bitwarden.desktop'
check-further-callbacks = true
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.microsoft.AzureVpnMac'
check-further-callbacks = true
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.att.ATTGNCMac'
check-further-callbacks = true
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.apple.MobileSMS'
check-further-callbacks = true
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'org.whispersystems.signal-desktop'
check-further-callbacks = true
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'cc.ffitch.shottr'
check-further-callbacks = true
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.citrix.CitrixReceiverLauncher'
check-further-callbacks = true
run = ['layout tiling']

[[on-window-detected]]
if.app-id = 'com.citrix.receiver.icaviewer.mac'
check-further-callbacks = true
run = ['layout tiling']
